"""empty message

Revision ID: 0f5fc599607a
Revises: cf831e5fe6f4
Create Date: 2025-06-03 20:21:18.140774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f5fc599607a'
down_revision = 'cf831e5fe6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('POST', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_text', sa.String(length=2200), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('POST', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('post_text')

    # ### end Alembic commands ###
